### ISSUE TITLE
Inserting users on sqlite failing

### ISSUE THREAD

**Issue by oculos** [eduMFA/eduMFA#202]
### Top-level intent

What did you try to achieve?
Add a user when using SQLite-based sqlresolver

### Steps to reproduce

1. I added an sqlresolver based on sqlite. This is my mapping: 
` { "userid" : "id", "username": "username" } `
2. When using "Test resolver", it tells me it found users on the sqlite database, which shows that it successfully connects to the database. 
3. However, adding user leads to a few errors. I also can't see any user on the user's list, though the testing function does say that they exist.

### Configuration

* **eduMFA version**:
latest
* **Installation method**: (from Ubuntu packages, github, PyPI, ...)
pip
* **Python version**:
4.12
* **Operating system**:
RHEL 9
* **Webserver**:
Nginx + gunicorn
* **Token database**: (MySQL, PostgreSQL, ...)
SQLite

### Log file

**Set EDUMFA_LOGLEVEL = logging.DEBUG in edumfa.cfg and take a look at the edumfa.log!**
**If appropriate, attach the log file or paste relevant portions.**

```
[2024-07-06 09:38:24,993][2631823][140511362746176][INFO][edumfa.lib.resolvers.SQLIdResolver:590] using the connect string sqlite:////etc/edumfa/uio.db
[2024-07-06 09:38:28,529][2631823][140511362746176][INFO][edumfa.lib.usercache:110] Deleted 0 entries from the user cache (resolver='sqlite', username=None, expired=None)
[2024-07-06 09:38:30,648][2631823][140511362746176][ERROR][edumfa.lib.user:744] AttributeError("'NoneType' object has no attribute 'columns'")
[2024-07-06 09:38:51,319][2631823][140511362746176][ERROR][edumfa.lib.resolvers.SQLIdResolver:348] Could not get the user ID: AttributeError("'NoneType' object has no attribute 'columns'")
[2024-07-06 09:38:51,379][2631823][140511362746176][INFO][edumfa.lib.resolvers.SQLIdResolver:630] Insert new user with attributes {'username': 'francisaugusto'}
[2024-07-06 09:38:51,380][2631823][140511362746176][ERROR][edumfa.app:838] Exception on /user/ [POST]
Traceback (most recent call last):
  File "/opt/edumfa/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/edumfa/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/edumfa/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/edumfa/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/api/auth.py", line 408, in decorated_function
    return f(*args, **kwargs)
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/api/lib/prepolicy.py", line 134, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/lib/event.py", line 100, in event_wrapper
    f_result = func(*args, **kwds)
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/api/user.py", line 284, in create_user_api
    r = create_user(resolvername, attributes, password=password)
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/lib/log.py", line 148, in log_wrapper
    return func(*args, **kwds)
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/lib/user.py", line 575, in create_user
    uid = y.add_user(attributes)
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/lib/resolvers/SQLIdResolver.py", line 631, in add_user
    r = self.session.execute(insert(self.TABLE).values(**kwargs))
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/sql/_dml_constructors.py", line 82, in insert
    return Insert(table)
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/sql/dml.py", line 1213, in __init__
    super().__init__(table)
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/sql/dml.py", line 987, in __init__
    self.table = coercions.expect(
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 396, in expect
    resolved = impl._literal_coercion(
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 604, in _literal_coercion
    self._raise_for_expected(element, argname)
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 693, in _raise_for_expected
    super()._raise_for_expected(
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 518, in _raise_for_expected
    raise exc.ArgumentError(msg, code=code) from err
sqlalchemy.exc.ArgumentError: subject table for an INSERT, UPDATE or DELETE expected, got None.
[2024-07-06 09:41:44,239][2631823][140511362746176][ERROR][edumfa.lib.resolvers.SQLIdResolver:348] Could not get the user ID: AttributeError("'NoneType' object has no attribute 'columns'")
```

**Comment by fritterhoff** [comment]
Will check that. Maybe one of the dependency upgrades broke the backend.

**Comment by fritterhoff** [comment]
So in a quick check, I can not reproduce the issue. Would you mind to send us a list of installed pip packages (`pip list`)
We migrated from SQLAlchemy 1.X to 2.X. 
I could imagine that something broke here...

**Comment by oculos** [comment]
Here it goes:

```
Package              Version
-------------------- ------------------
alembic              1.13.2
argon2-cffi          23.1.0
argon2-cffi-bindings 21.2.0
async-timeout        4.0.3
Babel                2.15.0
bcrypt               4.1.3
beautifulsoup4       4.12.3
blinker              1.8.2
cachetools           5.3.3
cbor2                5.6.4
certifi              2024.7.4
cffi                 1.16.0
charset-normalizer   3.3.2
click                8.1.7
configobj            5.0.8
croniter             2.0.5
cryptography         42.0.8
defusedxml           0.7.1
edumfa               2.1.0
Flask                3.0.3
flask-babel          4.0.0
Flask-Migrate        4.0.7
Flask-SQLAlchemy     3.1.1
Flask-Versioned      0.9.4.post20101221
google-auth          2.31.0
greenlet             3.0.3
grpcio               1.64.1
gunicorn             22.0.0
huey                 2.5.1
idna                 3.7
importlib_metadata   8.0.0
itsdangerous         2.2.0
Jinja2               3.1.4
ldap3                2.9.1
lxml                 5.2.2
Mako                 1.3.5
MarkupSafe           2.1.5
netaddr              1.3.0
packaging            24.1
passlib              1.7.4
pip                  24.0
pyasn1               0.6.0
pyasn1_modules       0.4.0
pycparser            2.22
pydash               8.0.1
PyJWT                2.8.0
PyMySQL              1.1.1
pyOpenSSL            24.1.0
pyrad                2.4
python-dateutil      2.9.0.post0
python-gnupg         0.5.2
pytz                 2024.1
PyYAML               6.0.1
redis                5.0.7
requests             2.32.3
rsa                  4.9
segno                1.6.1
setuptools           70.0.0
six                  1.16.0
smpplib              2.2.3
soupsieve            2.5
SQLAlchemy           2.0.31
typing_extensions    4.12.2
urllib3              2.2.2
Werkzeug             3.0.3
wheel                0.43.0
zipp                 3.19.2
```

**Comment by fritterhoff** [comment]
So that looks fine so far. Right now I have no real guess whats wrong about the resolver. 
What I am wondering a little bit: you claim to use python 4.12 (prop a typo and you mean 3.12?) but the stacktrace claims some issues in 3.9 paths...? Sure, we support 3.9 without any known limitations.
I will dig a little bit further into that issue the next days.

**Comment by oculos** [comment]
sorry, it was a typo.

**Comment by fritterhoff** [comment]
> sorry, it was a typo. 

So according to the stacktrace I would assume the guinicorn env ist a 3.9 version, so I would setup a 3.9 venv for my further debuggings.

**Comment by oculos** [comment]
(edumfa) ***@***.*** edumfa]# python --version
Python 3.9.18

I could test with a newer python version, actually. Should I?

**Comment by fritterhoff** [comment]
Let me check if I find something with 3.9 😉

**Comment by fritterhoff** [comment]
So. 3.9. does not seem to be the reason. Working fine for me.

**Comment by oculos** [comment]
Maybe it is my configuration? Although I don’t know why it would pass the test and still not return any users on the Users tab.

**Comment by fritterhoff** [comment]
I don't think its the config. Maybe we have some time later and debug it together.

**Comment by oculos** [comment]
Looking further to the error, I found this:

```
[2024-07-09 18:19:39,839][2999200][139691615057728][INFO][edumfa.lib.crypto:816] initializing HSM class: <class 'edumfa.lib.security.default.DefaultSecurityModule'>
[2024-07-09 18:19:39,839][2999200][139691615057728][INFO][edumfa.lib.crypto:248] Initialized HSM object {'obj': <edumfa.lib.security.default.DefaultSecurityModule object at 0x7f0c76f5f220>}
[2024-07-09 18:19:41,924][2999200][139691615057728][ERROR][edumfa.lib.user:744] TypeError('must be real number, not str')
[2024-07-09 18:19:57,911][2999200][139691615057728][INFO][edumfa.lib.resolvers.SQLIdResolver:631] Insert new user with attributes {'username': 'augusto'}
[2024-07-09 18:19:57,913][2999200][139691615057728][ERROR][edumfa.app:838] Exception on /user/ [POST]
Traceback (most recent call last):
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1815, in _execute_context
    context = constructor(
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 1457, in _init_compiled
    l_param: List[Any] = [
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 1459, in <listcomp>
    flattened_processors[key](compiled_params[key])
  File "lib/sqlalchemy/cyextension/processors.pyx", line 27, in sqlalchemy.cyextension.processors.to_float
ValueError: could not convert string to float: 'augusto'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/edumfa/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/edumfa/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/edumfa/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/edumfa/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/api/auth.py", line 408, in decorated_function
    return f(*args, **kwargs)
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/api/lib/prepolicy.py", line 134, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/lib/event.py", line 100, in event_wrapper
    f_result = func(*args, **kwds)
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/api/user.py", line 284, in create_user_api
    r = create_user(resolvername, attributes, password=password)
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/lib/log.py", line 148, in log_wrapper
    return func(*args, **kwds)
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/lib/user.py", line 575, in create_user
    uid = y.add_user(attributes)
  File "/opt/edumfa/lib/python3.9/site-packages/edumfa/lib/resolvers/SQLIdResolver.py", line 634, in add_user
    r = self.session.execute(insert(self.TABLE).values(**kwargs))
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2351, in execute
    return self._execute_internal(
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2245, in _execute_internal
    result = conn.execute(
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1821, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1815, in _execute_context
    context = constructor(
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 1457, in _init_compiled
    l_param: List[Any] = [
  File "/opt/edumfa/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 1459, in <listcomp>
    flattened_processors[key](compiled_params[key])
  File "lib/sqlalchemy/cyextension/processors.pyx", line 27, in sqlalchemy.cyextension.processors.to_float
sqlalchemy.exc.StatementError: (builtins.ValueError) could not convert string to float: 'augusto'
[SQL: INSERT INTO users (username) VALUES (?)]
[parameters: [{}]]
```
Can this be a SQLAlchemy bug?

**Comment by fritterhoff** [comment]
Sounds more like an issue in the database itself or an incorrect mapping

**Comment by oculos** [comment]
I thought so, but the database seems to be fine: 

sqlite> insert into users (username) VALUES ("francis");
sqlite> select * from users;
1|francis

**Comment by oculos** [comment]
Never mind, it must have been the db. I reconstructed it and it works now.
