### ISSUE TITLE
Errors when migrating database from privacyIDEA to eduMFA

### ISSUE THREAD

**Issue by hmt-leipzig** [eduMFA/eduMFA#354]
### Top-level intent

I am trying to migrate from privacyIDEA 3.8.1 to eduMFA 2.3.0. When I upgrade the database i get the following error.

### Steps to reproduce

1. copy the database of privacyIDEA to edumfa
2. verify database revision with `edumfa-manage db current -d /app/lib/edumfa/migrations` --> 006d4747f858
3. upgrade the database with `edumfa-manage db upgrade -d /app/lib/edumfa/migrations`

### Expected outcome

The database should be migrated to the newest version.

### Actual outcome

The database is stamped to newest version but it gets not migrated.

The following procedure helps to somewhat migrate the database, but appearently not completely because i get internal server errors on `validate/check` endpoint.

```
$# edumfa-manage db upgrade 4a0aec37e7cf -d /app/lib/edumfa/migrations/
$# edumfa-manage db stamp 5cb310101a1f -d /app/lib/edumfa/migrations/
$# edumfa-manage db upgrade 0d011e94a8e8 -d /app/lib/edumfa/migrations/
$# edumfa-manage db stamp 4a0aec37e7cf -d /app/lib/edumfa/migrations/
$# edumfa-manage db upgrade -d /app/lib/edumfa/migrations/
```

### Configuration

* **eduMFA version**: 2.3.0
* **Installation method**: PyPI
* **Python version**: 3.12
* **Operating system**: Alpine-Linux 
* **Webserver**: uwsgi
* **Token database**: PostgreSQL

### Log file

```
11669159a52e:/# edumfa-manage db upgrade -d /app/lib/edumfa/migrations/
Can not import grpc modules.
[2024-10-07 10:59:06,722][886][139641882536744][DEBUG][edumfa.app:234] Reading application from the static folder /app/lib/python3.12/site-packages/edumfa/static and the template folder static/templates/

               _       __  __ ______
              | |     |  \/  |  ____/\
       ___  __| |_   _| \  / | |__ /  \
      / _ \/ _` | | | | |\/| |  __/ /\ \
     |  __/ (_| | |_| | |  | | | / ____ \
      \___|\__,_|\__,_|_|  |_|_|/_/    \_\       v2.3.0

Running online
CurrentID in Table authcache: 0
 +++ Creating Sequence: authcache_seq
CurrentID in Table caconnector: 0
 +++ Creating Sequence: caconnector_seq
CurrentID in Table challenge: 0
 +++ Creating Sequence: challenge_seq
CurrentID in Table clientapplication: 22
 +++ Creating Sequence: clientapp_seq
Traceback (most recent call last):
  File "/app/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/app/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "edumfaserver" does not exist
LINE 2: FROM edumfaserver
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/bin/edumfa-manage", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/app/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/flask/cli.py", line 386, in decorator
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/flask_migrate/cli.py", line 154, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/app/lib/python3.12/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/app/lib/python3.12/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/app/lib/python3.12/site-packages/alembic/command.py", line 406, in upgrade
    script.run_env()
  File "/app/lib/python3.12/site-packages/alembic/script/base.py", line 586, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/app/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/app/lib/edumfa/migrations/env.py", line 110, in <module>
    run_migrations_online()
  File "/app/lib/edumfa/migrations/env.py", line 100, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/app/lib/python3.12/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/app/lib/python3.12/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/app/lib/edumfa/migrations/versions/5cb310101a1f_.py", line 45, in upgrade
    current_id = session.query(func.max(tbl.c.id)).one()[0] or 0
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2778, in one
    return self._iter().one()  # type: ignore
           ^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/app/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/app/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/app/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/app/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "edumfaserver" does not exist
LINE 2: FROM edumfaserver
             ^
```

**Comment by fritterhoff** [comment]
Hi,

so at least the `edumfa-manage db upgrade 0d011e94a8e8 -d /app/lib/edumfa/migrations/` should rename the `privacyserver` table to `edumfaserver`

There should be either an output telling you that this step was done or has failed?

**Comment by hmt-leipzig** [comment]
Hi, thanks for commenting.

under "Actual outcome" i described how to workaround the problem by some additional steps and manually applying revisions. This helps to bring the database i a "usable" state, although `edumfa-manage db check` gives the following error messages:

```
ERROR [flask_migrate] Error: New upgrade operations detected: [('remove_index', Index('ix_pidea_audit_date', Column('date', TIMESTAMP(), table=<mfa_audit>))), ('remove_index', Index('ix_pidea_audit_user', Column('user', VARCHAR(length=20), table=<mfa_audit>))), ('add_index', Index('ix_mfa_audit_date', Column('date', DateTime(), table=<mfa_audit>))), ('add_index', Index('ix_mfa_audit_user', Column('user', Unicode(length=20), table=<mfa_audit>))), [('modify_nullable', None, 'tokenrealm', 'id', {'existing_type': INTEGER(), 'existing_server_default': False, 'existing_comment': None}, False, True)], [('modify_nullable', None, 'tokentokengroup', 'id', {'existing_type': INTEGER(), 'existing_server_default': False, 'existing_comment': None}, False, True)]]
ERROR [flask_migrate] Error: New upgrade operations detected: [('remove_index', Index('ix_pidea_audit_date', Column('date', TIMESTAMP(), table=<mfa_audit>))), ('remove_index', Index('ix_pidea_audit_user', Column('user', VARCHAR(length=20), table=<mfa_audit>))), ('add_index', Index('ix_mfa_audit_date', Column('date', DateTime(), table=<mfa_audit>))), ('add_index', Index('ix_mfa_audit_user', Column('user', Unicode(length=20), table=<mfa_audit>))), [('modify_nullable', None, 'tokenrealm', 'id', {'existing_type': INTEGER(), 'existing_server_default': False, 'existing_comment': None}, False, True)], [('modify_nullable', None, 'tokentokengroup', 'id', {'existing_type': INTEGER(), 'existing_server_default': False, 'existing_comment': None}, False, True)]]
```

Also, when i start with a fresh database after initialisation when i run `edumfa db check` i get the following error messages:
```
ERROR [flask_migrate] Error: New upgrade operations detected: [[('modify_nullable', None, 'tokenrealm', 'id', {'existing_type': INTEGER(), 'existing_server_default': False, 'existing_comment': None}, False, True)], [('modify_nullable', None, 'tokentokengroup', 'id', {'existing_type': INTEGER(), 'existing_server_default': False, 'existing_comment': None}, False, True)]]
ERROR [flask_migrate] Error: New upgrade operations detected: [[('modify_nullable', None, 'tokenrealm', 'id', {'existing_type': INTEGER(), 'existing_server_default': False, 'existing_comment': None}, False, True)], [('modify_nullable', None, 'tokentokengroup', 'id', {'existing_type': INTEGER(), 'existing_server_default': False, 'existing_comment': None}, False, True)]]
```

**Comment by fritterhoff** [comment]
I was a bit confused since you write that it does not work

> The following procedure helps to somewhat migrate the database, but appearently not completely because i get internal server errors on validate/check endpoint.

Regarding the `edumfa-manage db check`. I'm not sure if the `edumfa-manage db check` is that meaningful. There is some delta yes but right now nothing I am realy worried about.

**Comment by hmt-leipzig** [comment]
Well it *does* not work - at least not as intended - and it took me quite a long time to figure out the steps to migrate to a database state where i can start the app.  Maybe it is a help for some other people facing the same problem.

Nevertheless this should be fixed to ensure migration from privacyIDEA works. The error I am facing now (#358) I can not be certain that it not happens because of this migration workaround.

**Comment by fritterhoff** [comment]
From my current knowledge several organizations successfully migrated the setup. There have been some minor issues but right now the most known issues should be fixed. Right now I don't have any idea what is wrong. 

The attached log is actually a migration that was used by privacyidea. So either the manual fixes broke something or we have to dig deeper into the migrations.

**Comment by fritterhoff** [comment]
Since we got no further update here we would close this issue.
