### ISSUE TITLE
Checking token with `pin_hash` migrated from privacyIDEA throws Exception

### ISSUE THREAD

**Issue by hmt-leipzig** [eduMFA/eduMFA#358]
### Top-level intent

Verify Token migrated from privacyIDEA. The token has a value in the table field `token.pin_hash`, although i don't know why. 

### Steps to reproduce

1. have a token with value in `token.pin_hash`
2. in the frontend go to *Token* -> *select Token*
3. in field "PIN und OTP eingeben, um Token zu prüfen." enter the Token and hit "Token testen"

### Expected outcome

verify the token as valid or invalid

### Actual outcome

An Exception in the logs.
### Configuration

* **eduMFA version**: 2.3.0
* **Installation method**: PyPI, official Docker-Image
* **Python version**: 3.12
* **Operating system**: Alpine-Linux, official Docker-Image
* **Webserver**: uwsgi, gunicorn
* **Token database**: PostgreSQL

### Log file
```
[2024-10-08 08:09:12,225][1318][140588036131712][DEBUG][edumfa.lib.resolvers.LDAPIdResolver:247] Reading '226566f0-9443-4905-afb2-4023c8fe5736' from cache for 'getUserInfo'
[2024-10-08 08:09:12,225][1318][140588036131712][DEBUG][edumfa.lib.resolvers.LDAPIdResolver:247] Reading 'us66zumi' from cache for 'getUserId'
[2024-10-08 08:09:12,368][1318][140588036131712][DEBUG][edumfa.lib.tokens.HMAC:178] Entering checkOtp with arguments (<edumfa.lib.tokens.HMAC.HmacOtp object at 0x7fdd2c9ba3f0>, '526412', 6) and keywords {'symetric': True}
[2024-10-08 08:09:12,368][1318][140588036131712][DEBUG][edumfa.lib.tokens.HMAC:154] OTP range counter: 57612251 - 57612263
[2024-10-08 08:09:12,369][1318][140588036131712][ERROR][edumfa.app:838] Exception on /validate/check [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/security/default.py", line 488, in decrypt
    data = unpadder.update(output) + unpadder.finalize()
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cryptography/hazmat/primitives/padding.py", line 160, in finalize
    result = _byte_unpadding_check(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cryptography/hazmat/primitives/padding.py", line 102, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/api/lib/postpolicy.py", line 101, in policy_wrapper
    response = wrapped_function(*args, **kwds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/api/lib/postpolicy.py", line 101, in policy_wrapper
    response = wrapped_function(*args, **kwds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/api/lib/postpolicy.py", line 101, in policy_wrapper
    response = wrapped_function(*args, **kwds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 10 more times]
  File "/usr/local/lib/python3.12/site-packages/edumfa/api/lib/decorators.py", line 42, in function_wrapper
    response = wrapped_function(*args, **kwds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/api/lib/prepolicy.py", line 134, in policy_wrapper
    return wrapped_function(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/api/lib/prepolicy.py", line 134, in policy_wrapper
    return wrapped_function(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/api/lib/prepolicy.py", line 134, in policy_wrapper
    return wrapped_function(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/decorators.py", line 109, in check_user_or_serial_in_request_wrapper
    f_result = func(*args, **kwds)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/subscriptions.py", line 189, in check_subscription_wrapper
    f_result = func(*args, **kwds)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/api/lib/prepolicy.py", line 134, in policy_wrapper
    return wrapped_function(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/event.py", line 100, in event_wrapper
    f_result = func(*args, **kwds)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/api/validate.py", line 407, in check
    success, details = check_serial_pass(serial, password, options=options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/log.py", line 148, in log_wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/policydecorators.py", line 76, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/policydecorators.py", line 427, in auth_lastauth
    res, reply_dict = wrapped_function(user_or_serial, passw, options)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/token.py", line 2000, in check_serial_pass
    res, reply_dict = check_token_list([tokenobject], passw,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/log.py", line 148, in log_wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/policydecorators.py", line 76, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/policydecorators.py", line 623, in reset_all_user_tokens
    r = wrapped_function(*args, **kwds)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/policydecorators.py", line 76, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/challengeresponsedecorators.py", line 156, in generic_challenge_response_reset_pin
    success, reply_dict = wrapped_function(*args, **kwds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/policydecorators.py", line 76, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/challengeresponsedecorators.py", line 189, in generic_challenge_response_resync
    success, reply_dict = wrapped_function(*args, **kwds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/token.py", line 2246, in check_token_list
    tokenobject.authenticate(passw, user, options=options)
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/decorators.py", line 47, in token_locked_wrapper
    f_result = func(*args, **kwds)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/tokenclass.py", line 491, in authenticate
    otp_counter = self.check_otp(otpval, options=options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/decorators.py", line 47, in token_locked_wrapper
    f_result = func(*args, **kwds)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/tokens/totptoken.py", line 336, in check_otp
    res = hmac2Otp.checkOtp(anOtpVal,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/log.py", line 187, in log_wrapper
    f_result = func(*args, **kwds)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/tokens/HMAC.py", line 156, in checkOtp
    otpval = self.generate(c)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/tokens/HMAC.py", line 122, in generate
    hmac = self.hmac(counter=counter, key=key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/tokens/HMAC.py", line 84, in hmac
    dig = self.secretObj.hmac_digest(data_input, self.hashfunc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/crypto.py", line 109, in hmac_digest
    self._setupKey_()
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/crypto.py", line 131, in _setupKey_
    akey = decrypt(self.val, self.iv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/log.py", line 148, in log_wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/crypto.py", line 383, in decrypt
    res = hsm.decrypt(to_bytes(enc_data), to_bytes(iv), key_id=key_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/edumfa/lib/security/default.py", line 497, in decrypt
    data = binascii.unhexlify(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Non-hexadecimal digit found
[2024-10-08 08:09:12,526][1318][140588036131712][DEBUG][edumfa.lib.auditmodules.base:178] Entering log with arguments (<edumfa.lib.auditmodules.sqlaudit.Audit object at 0x7fdd2c9fc6e0>, {'info': '500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.'}) and keywords {}
[2024-10-08 08:09:12,526][1318][140588036131712][DEBUG][edumfa.lib.auditmodules.base:191] Exiting log with result None
[2024-10-08 08:09:23 +0200] [1316] [INFO] Handling signal: winch
```

**Comment by hmt-leipzig** [comment]
This exception occurs when the encfile changes. 

Unfortunately i did not copy this binary(!) file appropriately. Therefore decryption failed and threw the Exception.

Closing
