### ISSUE TITLE
edumfa-manage config importer fails if there is a periodictask

### ISSUE THREAD

**Issue by bergerf** [eduMFA/eduMFA#378]
### Top-level intent

Bugfix

### Steps to reproduce

1. create and save a "Periodic Task"
(Its mandatory to choose a node at "Nodes", I can only choose "localnode".)
2. export the configuration: $ edumfa-manage config exporter | grep config > test.cfg
3. import the configuration: $ cat test.cfg | edumfa-manage config importer

code from the config:
```
'periodictask': [{'id': 2, 'name': 'count_simpleStats', 'active': True, 'interval': '0 6 * * *', 'nodes': ['localnode'], 'taskmodule': 'SimpleStats', 'retry_if_failed': True, 'last_update': '2024-10-16T07:12+0000', 'ordering': 0, 'options': {'assigned_tokens': 'True', 'hardware_tokens': 'True', 'software_tokens': 'True', 'total_tokens': 'True', 'unassigned_hardware_tokens': 'True', 'user_with_token': 'True'}, 'last_runs': {'localnode': datetime.datetime(2024, 10, 18, 4, 0, 2, 611708, tzinfo=tzutc())}}],
```

### Expected outcome

The imports works as known, without a periodictask the import was working.

### Actual outcome

The importer is failing with following error message:
```
(edumfa) edumfa@mfa-test:~$ cat test.cfg | edumfa-manage config importer
Can not import grpc modules.

               _       __  __ ______
              | |     |  \/  |  ____/\
       ___  __| |_   _| \  / | |__ /  \
      / _ \/ _` | | | | |\/| |  __/ /\ \
     |  __/ (_| | |_| | |  | | | / ____ \
      \___|\__,_|\__,_|_|  |_|_|/_/    \_\       v2.3.0

Traceback (most recent call last):
  File "/opt/edumfa/bin/edumfa-manage", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/flask/cli.py", line 386, in decorator
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/edumfa/commands/manage/config.py", line 96, in importer
    data = imp_fmt_dict[fmt](content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 110, in literal_eval
    return _convert(node_or_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 99, in _convert
    return dict(zip(map(_convert, node.keys),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 90, in _convert
    return list(map(_convert, node.elts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 99, in _convert
    return dict(zip(map(_convert, node.keys),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 99, in _convert
    return dict(zip(map(_convert, node.keys),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 109, in _convert
    return _convert_signed_num(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 83, in _convert_signed_num
    return _convert_num(node)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 74, in _convert_num
    _raise_malformed_node(node)
  File "/usr/lib/python3.11/ast.py", line 71, in _raise_malformed_node
    raise ValueError(msg + f': {node!r}')
ValueError: malformed node or string on line 1: <ast.Call object at 0x7fcb81f4df90>
(edumfa) edumfa@mfa-test:~$
```
If you remove the "periodictask" section from the config, the import works as expected.

### Configuration

* **eduMFA version**: 2.3.0
* **Installation method**: PyPI
* **Python version**: Python 3.11.2
* **Operating system**: Debian GNU/Linux 12 (bookworm)
* **Webserver**: Apache2
* **Token database**: PostgreSQL

### Log file

**Set EDUMFA_LOGLEVEL = logging.DEBUG in edumfa.cfg and take a look at the edumfa.log!**
**If appropriate, attach the log file or paste relevant portions.**

**Comment by fritterhoff** [comment]
Could you maybe try to use the `json` format?

**Comment by bergerf** [comment]
```
$ edumfa-manage config exporter -f json
Can not import grpc modules.

               _       __  __ ______
              | |     |  \/  |  ____/\
       ___  __| |_   _| \  / | |__ /  \
      / _ \/ _` | | | | |\/| |  __/ /\ \
     |  __/ (_| | |_| | |  | | | / ____ \
      \___|\__,_|\__,_|_|  |_|_|/_/    \_\       v2.3.0

Traceback (most recent call last):
  File "/opt/edumfa/bin/edumfa-manage", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/flask/cli.py", line 386, in decorator
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/edumfa/lib/python3.11/site-packages/edumfa/commands/manage/config.py", line 72, in exporter
    res = exp_fmt_dict.get(fmt.lower())(out) + '\n'
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

```
$ edumfa-manage config exporter -f json -o test.cfg
-> same export error
```

```
$ edumfa-manage config exporter -f json -t config -o test.cfg
-> OK
```

```
$ edumfa-manage config exporter -f yaml -t all -o test.cfg
-> seems OK
```

# import of this yaml file was ok, verification tests open

```
$ edumfa-manage config importer -t all -i test.cfg
Can not import grpc modules.

               _       __  __ ______
              | |     |  \/  |  ____/\
       ___  __| |_   _| \  / | |__ /  \
      / _ \/ _` | | | | |\/| |  __/ /\ \
     |  __/ (_| | |_| | |  | | | / ____ \
      \___|\__,_|\__,_|_|  |_|_|/_/    \_\       v2.3.0

Importing configuration type "resolver".
Importing configuration type "config".
Importing configuration type "caconnector".
Importing configuration type "realm".
Importing configuration type "smtpserver".
Importing configuration type "radiusserver".
Importing configuration type "policy".
Importing configuration type "event".
Importing configuration type "machineresolver".
Importing configuration type "smsgateway".
Importing configuration type "periodictask".
Importing configuration type "edumfaserver".
```

**Comment by fritterhoff** [comment]
Ok. I finally had some time to check this - sorry for the delay. The issue is not caused by the task itself but by the history of the task. 

As a workaround i would simply drop the last runs from the export?
