### ISSUE TITLE
sqlite3.OperationalError: no such table: config

### ISSUE THREAD

**Issue by ikreb7** [eduMFA/eduMFA#40]
### Top-level intent

Maybe this is also a problem with the broken db migration. But I don't know.

### Steps to reproduce

0. cat eduroamapp.py
```
import sys
sys.stdout = sys.stderr
from edumfa.app import create_app
# Now we can select the config file:
application = create_app(config_name="production", config_file="/etc/edumfa/pi.cfg")


if __name__ == "__main__":
    application.run(host="0.0.0.1)
```

2.` /opt/edumfa/venv/bin/uwsgi --http :8000 --master -b 32768 -p 4 --wsgi-file edumfaapp.py`

But the table exists:

```
mysql> select * from config;
+-------------------------------+-------------------------------------------------------------+--------+---------------------------------+
| Key                           | Value                                                       | Type   | Description                     |
+-------------------------------+-------------------------------------------------------------+--------+---------------------------------+
| __timestamp__                 | 1710767325                                                  |        | config timestamp. last changed. |
| email.tls                     | 0                                                           |        |                                 |
| hotp.hashlib                  | sha1                                                        | public |                                 |
| radius.dictfile               | /etc/privacyidea/dictionary                                 |        |                                 |
| remote.verify_ssl_certificate | 0                                                           |        |                                 |
| sms.Provider                  | privacyidea.lib.smsprovider.HttpSMSProvider.HttpSMSProvider |        |                                 |
| totp.hashlib                  | sha1                                                        | public |                                 |
| totp.timeShift                | 0                                                           |        |                                 |
| totp.timeStep                 | 30                                                          | public |                                 |
| totp.timeWindow               | 180                                                         | public |                                 |
+-------------------------------+-------------------------------------------------------------+--------+---------------------------------+
10 rows in set (0,00 sec)
```

Here is interesting, that the values aren't changed.

### Actual outcome

See Logs.

### Configuration

* **eduMFA version**: 1.4
* **Installation method**: pypi
* **Python version**: 3.10
* **Operating system**: Ubuntu
* **Webserver**: nginx
* **Token database**: MySQL
* 
### Log file

```
Traceback (most recent call last):
  File "/opt/edumfa/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/edumfa/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: config

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/edumfa/venv/lib/python3.10/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/edumfa/venv/lib/python3.10/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/edumfa/venv/lib/python3.10/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/edumfa/venv/lib/python3.10/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/edumfa/venv/lib/python3.10/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/opt/edumfa/venv/lib/python3.10/site-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/opt/edumfa/venv/lib/python3.10/site-packages/edumfa/webui/login.py", line 70, in before_request
    g.client_ip = get_client_ip(request, get_from_config(SYSCONF.OVERRIDECLIENT))
  File "/opt/edumfa/venv/lib/python3.10/site-packages/edumfa/lib/log.py", line 148, in log_wrapper
    return func(*args, **kwds)
  File "/opt/edumfa/venv/lib/python3.10/site-packages/edumfa/lib/config.py", line 364, in get_from_config
    config_object = get_config_object()
  File "/opt/edumfa/venv/lib/python3.10/site-packages/edumfa/lib/config.py", line 344, in get_config_object
    store['config_object'] = shared_config.reload_and_clone()
  File "/opt/edumfa/venv/lib/python3.10/site-packages/edumfa/lib/config.py", line 197, in reload_and_clone
    self._reload_from_db()
  File "/opt/edumfa/venv/lib/python3.10/site-packages/edumfa/lib/config.py", line 100, in _reload_from_db
    db_ts = Config.query.filter_by(Key=EDUMFA_TIMESTAMP).first()
  File "/opt/edumfa/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2824, in first
    return self.limit(1)._iter().first()
  File "/opt/edumfa/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/opt/edumfa/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/opt/edumfa/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/opt/edumfa/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/edumfa/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/edumfa/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/edumfa/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/opt/edumfa/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/edumfa/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/edumfa/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: config
[SQL: SELECT config."Key" AS "config_Key", config."Value" AS "config_Value", config."Type" AS "config_Type", config."Description" AS "config_Description" 
FROM config 
WHERE config."Key" = ?
 LIMIT ? OFFSET ?]
[parameters: ('__timestamp__', 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/edumfa/venv/lib/python3.10/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/edumfa/venv/lib/python3.10/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/edumfa/venv/lib/python3.10/site-packages/flask/app.py", line 1879, in handle_exception
    server_error = handler(server_error)
  File "/opt/edumfa/venv/lib/python3.10/site-packages/edumfa/api/before_after.py", line 410, in internal_error
    g.audit_object.log({"info": str(error)})
AttributeError: 'NoneType' object has no attribute 'log'
```

**Comment by ikreb7** [comment]
Also if you use a new database and install with ``edumfa-manage`` like:

1. edumfa-manage create_tables
2. edumfa-manage db stamp head -d venv/lib/edumfa/migrations/

and get this:

```
Can not import grpc modules.

               _       __  __ ______      
              | |     |  \/  |  ____/\    
       ___  __| |_   _| \  / | |__ /  \   
      / _ \/ _` | | | | |\/| |  __/ /\ \  
     |  __/ (_| | |_| | |  | | | / ____ \ 
      \___|\__,_|\__,_|_|  |_|_|/_/    \_          v1.4.0
        
Running online

```

But I get still the same error. The /etc/edumfa/edumfa.cfg contains:

`SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://edumfa:secret@localhost/edumfa'`

**Comment by ikreb7** [comment]
Thank you very much, I found the error. The script doesn't use internal the SQLALCHEMY_DATABASE_URI variable. This is the reason that the sqlite error occur.

Have a nice weekend.
