### ISSUE TITLE
tools/edumfa-migrate-linotp.py only working with SQLAlchemy < 2

### ISSUE THREAD

**Issue by cyber-simon** [eduMFA/eduMFA#430]
### Top-level intent

Migration from LinOTP to eduMFA

### Steps to reproduce

1. run tools/edumfa-migrate-linotp.py script
2. get error:
`
Traceback (most recent call last):
  File "/opt/edumfa/tools/./edumfa-migrate-linotp.py", line 586, in <module>
    main()
  File "/opt/edumfa/tools/./edumfa-migrate-linotp.py", line 576, in main
    migrate(config_obj)
  File "/opt/edumfa/tools/./edumfa-migrate-linotp.py", line 351, in migrate
    s = select([realm_table])
...
sqlalchemy.exc.ArgumentError: Column expression, FROM clause, or other columns clause element expected, got [Table('
`

### Expected outcome

Migrate Tokens from LinOTP database to eduMFA database.

### Actual outcome

Error message.

### Configuration

* **eduMFA version**: 2.3.0
* **Installation method**: PIP
* **Python version**: 3.9.2
* **Operating system**: Debian
* **Webserver**: Apache
* **Token database**:  PostgreSQL

### Log file

External tool. No logfile. 

### Workaround

Install second virtual env with eduMFA 2.0.3. I think, this is the last version with SQLAlchemy < 2. Seem like there are some API changes in SQLAlchemy that break the script.

**Comment by cyber-simon** [comment]
Seems like all the `select([ ... ])` should be changed to `select( ... )` and the following `for r in result:` to `for r in result.mappings():`. Don't know, if that's all, more testing next week.

**Comment by cyber-simon** [comment]
Did some testing. The changes seem to work, but the "autocommit" from SQLAlchemy 1.4 is gone. Needs some change to insert_chunk method. I'll try to do a pull request.
